remote_theme: "pmarsceill/just-the-docs"

title: Tub's Wiki
description: A Jekyll theme for documentation

permalink: pretty

color_scheme: dark
heading_anchors: true
nav_enabled: true
search_enabled: true

# Back to top link
back_to_top: false
back_to_top_text: "Back to top"

